'use client'
// import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

// import { Provider } from 'react-redux';
// import { store } from './store/store';

import Provider  from './StoreProvider';
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
    {/* // <Provider store={store}> */}
      <html lang="en">
        <body className={inter.className}>
          <SessionProvider>
             <Navbar />
            {children}
          </SessionProvider>
        </body>
        
      </html>
    {/* // </Provider> */}
    </Provider>
  );
}
